version: '3'
services:
  node-red:
    image: dwaiba/nodered
    ports:
      - 1880:1880
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10
